name: Automated Tests - Request and Response

on:
  workflow_dispatch:
    inputs:
      adminEnvironmentUrl:
        default: "https://reqres.in"
        description: "Request and Response Automation"
        required: true
      testSelection:
        description: "Select the tests to run"
        required: true
        type: choice
        options:
          - "All"
          - "Create User"
          - "Delete User"
          - "List Users"
          - "Update User"

env:
  DOMAIN_ADMIN: https://reqres.in
  PATH_ADMIN: reqres-automation
  TEST_PATH: ""

jobs:
  cypress-tests:
    name: Automation - ${{ github.event.inputs.testSelection }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Test Path
        run: |
          case "${{ github.event.inputs.testSelection }}" in
            "Create User")
              echo "TEST_PATH=cypress/e2e/create-user.cy.jsx" >> $GITHUB_ENV
              ;;
            "Delete User")
              echo "TEST_PATH=cypress/e2e/delete-user.cy.jsx" >> $GITHUB_ENV
              ;;
            "List Users")
              echo "TEST_PATH=cypress/e2e/list-users.cy.jsx" >> $GITHUB_ENV
              ;;
            "Update User")
              echo "TEST_PATH=cypress/e2e/update-user.cy.jsx" >> $GITHUB_ENV
              ;;
            "All")
              echo "TEST_PATH=cypress/e2e/**/*.cy.{js,jsx}" >> $GITHUB_ENV
              ;;
          esac

      - name: Install dependencies and Execute Cypress Tests
        run: |
          npm install
          export CYPRESS_BASE_URL=https://reqres.in
          npm run cypress:run -- --spec "${{ env.TEST_PATH }}"

      - name: List Cypress Output Files
        run: |
          echo "Listing all generated files in cypress directory:"
          ls -R cypress || echo "No files found."

      - name: Check if Screenshots exist
        run: |
          if [ "$(ls -A cypress/screenshots)" ]; then
            echo "Screenshots found"
          else
            echo "No screenshots found"
          fi

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: |
            cypress/videos/*.mp4

      - name: Upload Cypress Screenshots (if any)
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: |
            cypress/screenshots/*

      - name: Debug Artifact Upload
        run: |
          echo "Checking artifacts uploaded:"
          ls -R cypress/videos || echo "No video files found."
          ls -R cypress/screenshots || echo "No screenshot files found."

      - name: Send Test Results via Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "Cypress Test Results - ${{ github.event.inputs.testSelection }}"
          to: "diegospedroso@gmail.com"
          from: "diegospedroso@gmail.com"
          body: |
            The Cypress tests for selection `${{ github.event.inputs.testSelection }}` have been completed.
            Please find the attached artifacts for details.
          attachments: |
            cypress/videos/*.mp4
            cypress/screenshots/*
