jobs:
  cypress-tests:
    name: Automation - ${{ github.event.inputs.testSelection }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies and Execute Cypress Tests
        run: |
          npm install
          export CYPRESS_BASE_URL=https://reqres.in
          if [[ "${{ github.event.inputs.testSelection }}" == "All" ]]; then
            npm run cypress:run
          else
            npm run cypress:run -- --spec "${{ env.TEST_PATH }}"
          fi

      - name: Upload Cypress screenshots and videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots/
            cypress/videos/

      - name: Send email with Cypress results
        uses: mohammadreza/send-email@v1
        with:
          smtp_server: smtp.gmail.com
          smtp_port: 587
          smtp_username: ${{ secrets.GMAIL_USERNAME }}
          smtp_password: ${{ secrets.GMAIL_PASSWORD }}
          to: "destinatario@example.com"
          subject: "Cypress Test Results"
          body: |
            Hello,
            
            Please find the attached Cypress screenshots and videos of the latest test run.
            
            Best regards,
            Your Automation Team
          attachments: |
            cypress/screenshots/
            cypress/videos/
