name: Automated Tests - Request and Response

on:
  workflow_dispatch:
    inputs:
      adminEnvironmentUrl:
        default: "https://reqres.in"
        description: "Request and Response Automation"
        required: true
      testSelection:
        description: "Select the tests to run"
        required: true
        type: choice
        options:
          - "All"
          - "Create User"
          - "Delete User"
          - "List Users"
          - "Update User"
      email:
        description: "Email address to send the test results"
        required: true
        type: string
        default: "diegospedroso@gmail.com"

env:
  DOMAIN_ADMIN: https://reqres.in
  PATH_ADMIN: reqres-automation
  TEST_PATH: ""

jobs:
  cypress-tests:
    name: Automation - ${{ github.event.inputs.testSelection }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Test Path
        run: |
          declare -A testPaths
          testPaths=(
            ["Create User"]="cypress/e2e/create-user.cy.jsx"
            ["Delete User"]="cypress/e2e/delete-user.cy.jsx"
            ["List Users"]="cypress/e2e/list-users.cy.jsx"
            ["Update User"]="cypress/e2e/update-user.cy.jsx"
            ["All"]="cypress/e2e/**/*.cy.{js,jsx}"
          )
          echo "TEST_PATH=${testPaths[${{ github.event.inputs.testSelection }}]}" >> $GITHUB_ENV

      - name: Install dependencies and Execute Cypress Tests
        run: |
          npm install
          export CYPRESS_BASE_URL=https://reqres.in
          npm run cypress:run -- --spec "${{ env.TEST_PATH }}"

      - name: Check and Upload Cypress Artifacts
        run: |
          for dir in videos screenshots; do
            if [ "$(ls -A cypress/$dir)" ]; then
              echo "$dir found"
              ls -R cypress/$dir
              actions/upload-artifact@v4
              with:
                name: cypress-$dir
                path: cypress/$dir/*
            else
              echo "No $dir found"
            fi
          done

      - name: Send Test Results via Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "Cypress Test Results - ${{ github.event.inputs.testSelection }}"
          to: ${{ github.event.inputs.email }}
          from: "diegospedroso@gmail.com"
          body: |
            The Cypress tests for selection `${{ github.event.inputs.testSelection }}` have been completed.
            Please find the attached artifacts for details.
          attachments: |
            cypress/videos/*.mp4
            cypress/screenshots/*
